// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: counter.proto

package counter

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type IncreaseRequest struct {
	Data                 *PointData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IncreaseRequest) Reset()         { *m = IncreaseRequest{} }
func (m *IncreaseRequest) String() string { return proto.CompactTextString(m) }
func (*IncreaseRequest) ProtoMessage()    {}
func (*IncreaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75dcd656fce7132f, []int{0}
}
func (m *IncreaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncreaseRequest.Unmarshal(m, b)
}
func (m *IncreaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncreaseRequest.Marshal(b, m, deterministic)
}
func (m *IncreaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseRequest.Merge(m, src)
}
func (m *IncreaseRequest) XXX_Size() int {
	return xxx_messageInfo_IncreaseRequest.Size(m)
}
func (m *IncreaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseRequest proto.InternalMessageInfo

func (m *IncreaseRequest) GetData() *PointData {
	if m != nil {
		return m.Data
	}
	return nil
}

type IncreaseResponse struct {
	Data                 *PointData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code                 int64      `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IncreaseResponse) Reset()         { *m = IncreaseResponse{} }
func (m *IncreaseResponse) String() string { return proto.CompactTextString(m) }
func (*IncreaseResponse) ProtoMessage()    {}
func (*IncreaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75dcd656fce7132f, []int{1}
}
func (m *IncreaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncreaseResponse.Unmarshal(m, b)
}
func (m *IncreaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncreaseResponse.Marshal(b, m, deterministic)
}
func (m *IncreaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseResponse.Merge(m, src)
}
func (m *IncreaseResponse) XXX_Size() int {
	return xxx_messageInfo_IncreaseResponse.Size(m)
}
func (m *IncreaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseResponse proto.InternalMessageInfo

func (m *IncreaseResponse) GetData() *PointData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *IncreaseResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *IncreaseResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DecreaseRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecreaseRequest) Reset()         { *m = DecreaseRequest{} }
func (m *DecreaseRequest) String() string { return proto.CompactTextString(m) }
func (*DecreaseRequest) ProtoMessage()    {}
func (*DecreaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75dcd656fce7132f, []int{2}
}
func (m *DecreaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecreaseRequest.Unmarshal(m, b)
}
func (m *DecreaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecreaseRequest.Marshal(b, m, deterministic)
}
func (m *DecreaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecreaseRequest.Merge(m, src)
}
func (m *DecreaseRequest) XXX_Size() int {
	return xxx_messageInfo_DecreaseRequest.Size(m)
}
func (m *DecreaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecreaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecreaseRequest proto.InternalMessageInfo

func (m *DecreaseRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *DecreaseRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DecreaseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecreaseResponse) Reset()         { *m = DecreaseResponse{} }
func (m *DecreaseResponse) String() string { return proto.CompactTextString(m) }
func (*DecreaseResponse) ProtoMessage()    {}
func (*DecreaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75dcd656fce7132f, []int{3}
}
func (m *DecreaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecreaseResponse.Unmarshal(m, b)
}
func (m *DecreaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecreaseResponse.Marshal(b, m, deterministic)
}
func (m *DecreaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecreaseResponse.Merge(m, src)
}
func (m *DecreaseResponse) XXX_Size() int {
	return xxx_messageInfo_DecreaseResponse.Size(m)
}
func (m *DecreaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DecreaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DecreaseResponse proto.InternalMessageInfo

type PointData struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty" gorm:"primay_key;AUTO_INCREMENT"`
	UserID               int64    `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointData) Reset()         { *m = PointData{} }
func (m *PointData) String() string { return proto.CompactTextString(m) }
func (*PointData) ProtoMessage()    {}
func (*PointData) Descriptor() ([]byte, []int) {
	return fileDescriptor_75dcd656fce7132f, []int{4}
}
func (m *PointData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointData.Unmarshal(m, b)
}
func (m *PointData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointData.Marshal(b, m, deterministic)
}
func (m *PointData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointData.Merge(m, src)
}
func (m *PointData) XXX_Size() int {
	return xxx_messageInfo_PointData.Size(m)
}
func (m *PointData) XXX_DiscardUnknown() {
	xxx_messageInfo_PointData.DiscardUnknown(m)
}

var xxx_messageInfo_PointData proto.InternalMessageInfo

func (m *PointData) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PointData) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *PointData) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*IncreaseRequest)(nil), "counter.IncreaseRequest")
	proto.RegisterType((*IncreaseResponse)(nil), "counter.IncreaseResponse")
	proto.RegisterType((*DecreaseRequest)(nil), "counter.DecreaseRequest")
	proto.RegisterType((*DecreaseResponse)(nil), "counter.DecreaseResponse")
	proto.RegisterType((*PointData)(nil), "counter.PointData")
}

func init() { proto.RegisterFile("counter.proto", fileDescriptor_75dcd656fce7132f) }

var fileDescriptor_75dcd656fce7132f = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0x4e, 0x5b, 0x02, 0x61, 0x0c, 0x81, 0xac, 0x89, 0xa9, 0x5c, 0x6c, 0x36, 0xc6, 0x70, 0x11,
	0x12, 0xf4, 0xa2, 0x9e, 0x90, 0x72, 0xe0, 0x20, 0x9a, 0x15, 0xcf, 0x64, 0x29, 0x63, 0x69, 0x4c,
	0xbb, 0xb0, 0xbb, 0x35, 0xe1, 0x71, 0x7c, 0x31, 0x1f, 0xc2, 0x27, 0x30, 0x6c, 0x5b, 0xc0, 0x46,
	0x13, 0x6f, 0xf3, 0xcd, 0xe4, 0xfb, 0xe9, 0xd7, 0x85, 0x46, 0x20, 0xd2, 0x44, 0xa3, 0xec, 0xae,
	0xa4, 0xd0, 0x82, 0xd4, 0x72, 0xd8, 0xbe, 0x0c, 0x23, 0xbd, 0x4c, 0xe7, 0xdd, 0x40, 0xc4, 0xbd,
	0x50, 0x84, 0xa2, 0x67, 0xee, 0xf3, 0xf4, 0xd5, 0x20, 0x03, 0xcc, 0x94, 0xf1, 0xe8, 0x0d, 0x34,
	0xc7, 0x49, 0x20, 0x91, 0x2b, 0x64, 0xb8, 0x4e, 0x51, 0x69, 0x72, 0x01, 0x95, 0x05, 0xd7, 0xdc,
	0xb5, 0x3c, 0xab, 0x73, 0xd4, 0x27, 0xdd, 0xc2, 0xe8, 0x49, 0x44, 0x89, 0xf6, 0xb9, 0xe6, 0xcc,
	0xdc, 0xe9, 0x12, 0x5a, 0x7b, 0xaa, 0x5a, 0x89, 0x44, 0xe1, 0x7f, 0xb9, 0x84, 0x40, 0x25, 0x10,
	0x0b, 0x74, 0x6d, 0xcf, 0xea, 0x38, 0xcc, 0xcc, 0xc4, 0x85, 0x5a, 0x8c, 0x4a, 0xf1, 0x10, 0x5d,
	0xc7, 0xb3, 0x3a, 0x75, 0x56, 0x40, 0x3a, 0x80, 0xa6, 0x8f, 0x3f, 0x43, 0x9e, 0x40, 0x35, 0x55,
	0x28, 0xc7, 0xbe, 0xb1, 0x72, 0x58, 0x8e, 0xb6, 0x7b, 0x1e, 0x6f, 0x4d, 0x73, 0xe9, 0x1c, 0x51,
	0x02, 0xad, 0xbd, 0x44, 0x16, 0x96, 0xae, 0xa1, 0xbe, 0xcb, 0x45, 0xae, 0xc1, 0x2e, 0xc4, 0xee,
	0xcf, 0xbf, 0x3e, 0xcf, 0xbc, 0x50, 0xc8, 0xf8, 0x96, 0xae, 0x64, 0x14, 0xf3, 0xcd, 0xec, 0x0d,
	0x37, 0x77, 0x83, 0x97, 0xe9, 0xe3, 0x6c, 0x3c, 0x19, 0xb2, 0xd1, 0xc3, 0x68, 0x32, 0xa5, 0xcc,
	0xce, 0xec, 0xf2, 0x18, 0xf6, 0x1f, 0x31, 0x9c, 0xc3, 0x18, 0xfd, 0x0f, 0x0b, 0x8e, 0x87, 0x59,
	0x27, 0xc6, 0xfa, 0x19, 0xe5, 0x7b, 0x14, 0x20, 0xf1, 0xa1, 0x51, 0x74, 0x69, 0xf6, 0xc4, 0xdd,
	0x55, 0x57, 0xfa, 0x3d, 0xed, 0xd3, 0x5f, 0x2e, 0x79, 0xfb, 0x3e, 0x34, 0x8a, 0x8f, 0x2c, 0xab,
	0x94, 0xfa, 0x3b, 0x50, 0x29, 0xd7, 0x32, 0xaf, 0x9a, 0x97, 0x71, 0xf5, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0xd1, 0x8b, 0xbc, 0x0e, 0x62, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CounterPointServiceClient is the client API for CounterPointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CounterPointServiceClient interface {
	IncreasePoint(ctx context.Context, in *IncreaseRequest, opts ...grpc.CallOption) (*IncreaseResponse, error)
	DecreasePoint(ctx context.Context, in *DecreaseRequest, opts ...grpc.CallOption) (*DecreaseResponse, error)
}

type counterPointServiceClient struct {
	cc *grpc.ClientConn
}

func NewCounterPointServiceClient(cc *grpc.ClientConn) CounterPointServiceClient {
	return &counterPointServiceClient{cc}
}

func (c *counterPointServiceClient) IncreasePoint(ctx context.Context, in *IncreaseRequest, opts ...grpc.CallOption) (*IncreaseResponse, error) {
	out := new(IncreaseResponse)
	err := c.cc.Invoke(ctx, "/counter.CounterPointService/IncreasePoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterPointServiceClient) DecreasePoint(ctx context.Context, in *DecreaseRequest, opts ...grpc.CallOption) (*DecreaseResponse, error) {
	out := new(DecreaseResponse)
	err := c.cc.Invoke(ctx, "/counter.CounterPointService/DecreasePoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CounterPointServiceServer is the server API for CounterPointService service.
type CounterPointServiceServer interface {
	IncreasePoint(context.Context, *IncreaseRequest) (*IncreaseResponse, error)
	DecreasePoint(context.Context, *DecreaseRequest) (*DecreaseResponse, error)
}

// UnimplementedCounterPointServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCounterPointServiceServer struct {
}

func (*UnimplementedCounterPointServiceServer) IncreasePoint(ctx context.Context, req *IncreaseRequest) (*IncreaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncreasePoint not implemented")
}
func (*UnimplementedCounterPointServiceServer) DecreasePoint(ctx context.Context, req *DecreaseRequest) (*DecreaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecreasePoint not implemented")
}

func RegisterCounterPointServiceServer(s *grpc.Server, srv CounterPointServiceServer) {
	s.RegisterService(&_CounterPointService_serviceDesc, srv)
}

func _CounterPointService_IncreasePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncreaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterPointServiceServer).IncreasePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/counter.CounterPointService/IncreasePoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterPointServiceServer).IncreasePoint(ctx, req.(*IncreaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounterPointService_DecreasePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecreaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterPointServiceServer).DecreasePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/counter.CounterPointService/DecreasePoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterPointServiceServer).DecreasePoint(ctx, req.(*DecreaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CounterPointService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "counter.CounterPointService",
	HandlerType: (*CounterPointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IncreasePoint",
			Handler:    _CounterPointService_IncreasePoint_Handler,
		},
		{
			MethodName: "DecreasePoint",
			Handler:    _CounterPointService_DecreasePoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "counter.proto",
}
